# Generated by Django 5.2 on 2025-04-14 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_loginuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('instructor', 'Instructor'), ('student', 'Student'), ('sponsor', 'Sponsor')], default='member', max_length=10),
        ),
    ]
