# Generated by Django 5.2 on 2025-04-14 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_loginuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('instructor', 'Instructor'), ('student', 'Student'), ('sponsor', 'Sponsor')], default='student', max_length=10),
        ),
    ]
