# Generated by Django 5.2 on 2025-04-11 12:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodle', '0002_alter_enrollment_enrollment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsorship',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sponsors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sponsorship',
            name='sponsor',
            field=models.ForeignKey(limit_choices_to={'role': 'SPONSOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='sponsored_students', to=settings.AUTH_USER_MODEL),
        ),
    ]
