# Generated by Django 5.2 on 2025-04-14 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodle', '0010_alter_course_instructor_alter_enrollment_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='write_assignment',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
