# Generated by Django 5.2 on 2025-04-14 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodle', '0011_assignment_write_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='write_assignment',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
