# Generated by Django 5.2 on 2025-04-17 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodle', '0013_assignment_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsorship',
            name='sponsorship_impact',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
