# Generated by Django 5.2 on 2025-04-19 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodle', '0016_alter_progressreport_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progressreport',
            name='enrollment',
        ),
        migrations.AlterField(
            model_name='progressreport',
            name='remarks',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
