# Generated by Django 5.2 on 2025-04-23 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moodle', '0017_remove_progressreport_enrollment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='created_at',
            new_name='made_at',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
