# Generated by Django 5.2 on 2025-04-23 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodle', '0018_rename_created_at_course_made_at_delete_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('COMPLETED', 'Completed'), ('INACTIVE', 'Inactive'), ('Running', 'Advanced')], max_length=12)),
                ('completion_rate', models.FloatField(default=0, null=True)),
                ('message', models.CharField(max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moodle.course')),
            ],
        ),
    ]
