# Generated by Django 5.2 on 2025-04-23 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodle', '0019_coursestatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursestatus',
            name='status',
            field=models.CharField(choices=[('COMPLETED', 'Completed'), ('INACTIVE', 'Inactive'), ('RUNNING', 'Running')], max_length=12),
        ),
    ]
